language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t acesic/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true acesic/docker-react npm run test


