language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t acesic/docker-react -f Dockerfile.dev .
  - docker run acesic/docker-react

script:
  - docker run acesic/docker-react npm run test -- --coverage

